name: breezr_flutter
description: "Breezr"

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  bloc: ^9.0.0
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  equatable: ^2.0.7
  fl_chart: ^0.71.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  flutter_localizations:
    sdk: flutter
  flutter_rust_bridge: 2.9.0
  flutter_secure_storage: ^9.2.4
  forui: ^0.10.0+1
  forui_assets: ^0.10.0
  freezed_annotation: ^3.0.0
  get_it: ^8.0.3
  handy_extensions: ^0.2.23
  injectable: ^2.5.0
  intl: ^0.19.0
  json_annotation: ^4.9.0
  package_info_plus: ^8.3.0
  path: ^1.9.1
  path_provider: ^2.1.5
  permission_handler: ^12.0.0+1
  sentry_flutter: ^8.14.2
  sentry_logging: ^8.14.2
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.15
  freezed: ^3.0.6
  injectable_generator: ^2.7.0
  json_serializable: ^6.9.5
  mocktail: ^1.0.4
  very_good_analysis: ^7.0.0

flutter:
  uses-material-design: true
