// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.9.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'lib.dart';
import 'models.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `wrap_api`

Future<ApiResponse> scanCache() => RustLib.instance.api.crateBridgeScanCache();

Future<ApiResponse> scanLogs() => RustLib.instance.api.crateBridgeScanLogs();

Future<ApiResponse> scanTrash() => RustLib.instance.api.crateBridgeScanTrash();

Future<ApiResponse> cleanItems({required List<JunkItem> items}) =>
    RustLib.instance.api.crateBridgeCleanItems(items: items);

/// Return the current user’s home directory.
///
/// * macOS/Linux:  reads `$HOME`
///
/// Falls back to the root of the drive (`/`) if none is set.
Future<PathBuf> getUserHomeDirectory() =>
    RustLib.instance.api.crateBridgeGetUserHomeDirectory();
